export default {
  // Fetching
  SAVE_PRODUCTS: 'SAVE_PRODUCTS',
  SAVE_CATEGORIES: 'SAVE_CATEGORIES',

  // Interface
  SET_FRAME: 'SET_FRAME',
  SET_CURRENCY: 'SET_CURRENCY',

  // Cart
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',

  // Order
  UPDATE_ORDER: 'UPDATE_ORDER',

  // Purchase History
  UPDATE_PURCHASE_HISTORY: 'UPDATE_PURCHASE_HISTORY'
};
